### ISSUE TITLE
python3.6

### ISSUE THREAD

**Issue by ehgen0ng** [hanhan-GKD/ydxx-terminal#1]
Traceback (most recent call last):
  File "yundingxx-terminal/main.py", line 5, in <module>
    import urwid
  File "/usr/local/lib/python3.6/site-packages/urwid/__init__.py", line 26, in <module>
    from urwid.widget import (FLOW, BOX, FIXED, LEFT, RIGHT, CENTER, TOP, MIDDLE,
  File "/usr/local/lib/python3.6/site-packages/urwid/widget.py", line 27, in <module>
    from urwid.util import (MetaSuper, decompose_tagmarkup, calc_width,
  File "/usr/local/lib/python3.6/site-packages/urwid/util.py", line 61, in <module>
    detected_encoding = detect_encoding()
  File "/usr/local/lib/python3.6/site-packages/urwid/util.py", line 58, in detect_encoding
    locale.setlocale(locale.LC_ALL, initial)
  File "/usr/local/lib/python3.6/locale.py", line 598, in setlocale
    return _setlocale(category, locale)
locale.Error: unsupported locale setting

**Comment by ehgen0ng** [comment]
export LC_ALL=C
